### ISSUE TITLE
 [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]

### ISSUE THREAD

**Issue by linhertz** [veighna-global/vnpy_bybit#10]
params: None
data: None
response:

Exception trace:
Traceback (most recent call last):
  File "C:\veighna_studio\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "C:\veighna_studio\lib\asyncio\base_events.py", line 1097, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\veighna_studio\lib\asyncio\base_events.py", line 1127, in _create_connection_transport
    await waiter
  File "C:\veighna_studio\lib\asyncio\sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\veighna_studio\lib\asyncio\sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\veighna_studio\lib\ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\veighna_studio\lib\site-packages\vnpy_rest\rest_client.py", line 262, in _process_request
    response: Response = await self._get_response(request)
  File "C:\veighna_studio\lib\site-packages\vnpy_rest\rest_client.py", line 244, in _get_response
    cr: ClientResponse = await self.session.request(
  File "C:\veighna_studio\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\veighna_studio\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\veighna_studio\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\veighna_studio\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "C:\veighna_studio\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\veighna_studio\lib\site-packages\aiohttp\connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.bybit.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]

**Comment by linhertz** [comment]
我自己改到old version 出现的问题，没有安装vnpy_evo
