### ISSUE TITLE
TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by linhertz** [veighna-global/vnpy_bybit#11]
Traceback (most recent call last):
  File "C:\veighna_studio\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\veighna_studio\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\veighna_studio\lib\site-packages\vnpy\event\engine.py", line 60, in _run
    self._process(event)
  File "C:\veighna_studio\lib\site-packages\vnpy\event\engine.py", line 73, in _process
    [handler(event) for handler in self._handlers[event.type]]
  File "C:\veighna_studio\lib\site-packages\vnpy\event\engine.py", line 73, in <listcomp>
    [handler(event) for handler in self._handlers[event.type]]
  File "C:\veighna_studio\lib\site-packages\vnpy_optionmaster\engine.py", line 197, in process_contract_event
    portfolio.add_option(contract)
  File "C:\veighna_studio\lib\site-packages\vnpy_optionmaster\base.py", line 652, in add_option
    option: OptionData = OptionData(contract)
  File "C:\veighna_studio\lib\site-packages\vnpy_optionmaster\base.py", line 100, in __init__
    self.days_to_expiry: int = calculate_days_to_expiry(
  File "C:\veighna_studio\lib\site-packages\vnpy_optionmaster\time.py", line 21, in calculate_days_to_expiry
    while current_dt < option_expiry:
TypeError: can't compare offset-naive and offset-aware datetimes

**Comment by veighna-global** [comment]
OptionMaster app is not supported by VeighNa Evo.
